#Nombre del workflow
name: "Hola Mundo"

#Eventos que inician el workflow
on:
  push:
    branches: ["main"]

#Job (unidad de trabajo) asociado al sistema operativo
jobs:
  primer_job:
    runs-on: ubuntu-latest

    #Pasos o acciones individuales dentro del Job
    steps:
      - name: Hola Mundo
        run: echo "Hola Primer Mundo"
      - run: cat hola.php

      - run: echo "Hacemos pull del c贸digo"
      - run: echo "Correr migraciones"
      - run: echo "Generar binario"
      - run: echo "Publicar versi贸n"
      - run: pwd
      - run: whoami
      - run: cat /etc/os-release
      
  segundo_job:
    #Se coloca una dependencia para ejecutar el segundo job (debe terminar el primer job)
    needs: primer_job
    runs-on: ubuntu-latest

    #Pasos o acciones individuales dentro del Job
    steps:
      - name: Hola Mundo
        run: echo "Hola Segundo Mundo"
        
      - run: echo "Hacemos pull del c贸digo"
      - run: echo "Correr migraciones"
      - run: echo "Generar binario"
      - run: echo "Publicar versi贸n"
      - run: pwd
      - run: whoami
      - run: cat /etc/os-release