#Nombre del workflow
name: "Hola Mundo"

#Eventos que inician el workflow
on:
  push:
    branches: ["main"]

#Job (unidad de trabajo) asociado al sistema operativo
jobs:
  primer_job:
    runs-on: ubuntu-latest

    #Se agregan variables de entorno
    env:
      NAME: Código Facilito

    #Pasos o acciones individuales dentro del Job
    steps:
      - name: Hola Mundo
        run: echo "Hola Primer Mundo"
      #- run: cat hola.php
      - run: echo "Hola $NAME"

      - run: echo "Hacemos pull del código"
      - run: echo "Correr migraciones"
      - run: echo "Generar binario"
      - run: echo "Publicar versión"
      - run: pwd
      - run: whoami
      - run: cat /etc/os-release
      
  segundo_job:
    #Se forza que el segundo job no se ejecute a base de una condición if
    #if: false
    #Se agrega una condición del nombre de la rama
    if: ${{ github.ref == 'refs/heads/main'}}

    #Se coloca una dependencia para ejecutar el segundo job (debe terminar el primer job)
    needs: primer_job
    runs-on: ubuntu-latest

    #Pasos o acciones individuales dentro del Job
    steps:
      - name: Hola Mundo
        run: echo "Hola Segundo Mundo"
        
      - run: echo "Hacemos pull del código"
      - run: echo "Correr migraciones"
      - run: echo "Generar binario"
      - run: echo "Publicar versión"
      - run: pwd
      - run: whoami
      - run: cat /etc/os-release
      #Se imprime la referencia
      - run: echo ${{ github.ref}}