name: Integración Continua

on: push

jobs:
  first_job:
    runs-on: ubuntu-latest

    #Utilizar servicio redis en una maquina virtual (eso se haace a nivel job)
    #services: 
    #  redis:
    #    image: redis
    #    ports:
    #      - 6379:6379

    steps:
      #Imprimir secretos de entorno
      - name: Print secret
        run: echo "${{ secrets.TOKEN_SECRET }}"

      #Instalr node 18 desde github marketplace
      - name: setup node
        uses: actions/setup-node@v4
        with: 
          node-version: '18'

      #Instalar redis cli
      #- name: Instal redis cli
      #  run: sudo apt-get update -y && sudo apt-get install redis-tools -y

      #Se manda el test de conexión de redis
      #- name: Test redis
      #  run: redis-cli -h localhost -p 6379 ping

      #Se agrega el repositorio
      - name: Checkout
        uses: actions/checkout@v4

      #Se instala dependencia npm
      - name: Instalar dependencias
        run: npm install

      #Se ejecutan los test
      - name: Run test
        run: npm run test