name: Integración Continua

on: push

jobs:
  first_job:
    runs-on: ubuntu-latest

    #Utilizar servicio redis en una maquina virtual (eso se haace a nivel job)
    services: 
      redis:
        image: redis
        ports:
          - 6379:6379

    steps:
      #Imprimir secretos de entorno
      - name: Print secret
        run: echo "${{ secrets.TOKEN_SECRET }}"

      #Instalr node 18 desde github marketplace
      - name: setup node
        uses: actions/setup-node@v4
        with: 
          node-version: '18'

      - name: Instal redis cli
        run: sudo apt-get update -y && apt-get install redis-tools -y
