name: Integración Continua

on: push

jobs:
  first_job:
    runs-on: ubuntu-latest

    #Imprimir variables de entorno
    steps:
      - name: Print variable
        run: echo "${{ secrets.TOKEN_SECRET }}"