name: Deploy to server

  on:
    push:

  jobs: 
    primer_job:
      runs-on: ubuntu-latest

      strategy:
        matrix:
          message: ["Hola","codigoFacilito","Bootcamp Github Action"]

      steps:
      - name: Print mensaje
      - run: echo "${{ matrix.message }}"
